import Head from 'next/head'
import Feed from "./components/Feed"
import Header from './components/Header'

export default function Home() {
  return (
    <div className="bg-gray-50 h-screen overflow-scroll scrollbar-hide">
      <Head>
        <title>Instagram 2.0 Built with Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>
      
      <Feed/>
  
    </div>
  )
}
